development:
  adapter: postgresql
  encoding: unicode
  database: nrcc_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: nrcc_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: nrcc_production
  pool: 5
